# Generated by Django 6.0.4 on 2026-05-05 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['name'], 'verbose_name': 'Board', 'verbose_name_plural': 'Boards'},
        ),
    ]
